version: "2"
services:
  server:
    build: .
    environment:
      VIRTUAL_HOST: harvester.docker
      SYMFONY_ENV: dev
      SYMFONY_DEBUG: 1
      SYMFONY__KERNEL__CACHE_DIR: /tmp/cache
      COMPOSER_MEMORY_LIMIT: -1
    ports:
      - '80'
    volumes:
      - './data/:/data/'
      - './src:/harvester/src'
      - './vendor:/harvester/vendor'
