version: "2"
services:
  harvester:
    build: .
    environment:
      VIRTUAL_HOST: harvester.docker
      SYMFONY_ENV: dev
      SYMFONY_DEBUG: 1
    ports:
      - '80'
    volumes:
      - './data/:/data/'
      - './src:/harvester/src'
      - './vendor:/harvester/vendor'
