version: "2"
services:
  composer:
    build: docker/composer
    volumes:
      - '.:/app'
      - './docker/composer-cache:/composer/cache'
  harvester:
    build: .
    volumes:
      - './src:/harvester/src'
      - './vendor:/harvester/vendor'
    volumes_from:
      - db
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        HARVESTER_HARVEST_USER: ${HARVESTER_HARVEST_USER}
        HARVESTER_HARVEST_PASSWORD: ${HARVESTER_HARVEST_PASSWORD}
        HARVESTER_HARVEST_ACCOUNT: ${HARVESTER_HARVEST_ACCOUNT}
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
