security:
    encoders:
        Harvester\FetchBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        user_db:
          entity: { class: Harvester\FetchBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~


            provider: user_db
            form_login:
              login_path: _admin_login
              check_path: _admin_login_check
              always_use_default_target_path: true
              default_target_path: _useredit
            logout:
                path:   /logout
                target: /admin

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
