#!/bin/bash

# Write config file.
cd /harvester
cat > /harvester/app/config/parameters.yml <<EOF
parameters:
  database_path:     /data/harvester.sqlite

  mailer_transport:  smtp
  mailer_host:       127.0.0.1
  mailer_user:       ~
  mailer_password:   ~
    
  locale:            en
  secret:            $HARVESTER_SECRET
    
  default_hours_per_day:  $HARVESTER_HOURS_PER_DAY
  default_billability_goal: $HARVESTER_BILLABILITY_GOAL
    
mattvick_harvest_app:
  user:      '$HARVESTER_HARVEST_USER'
  password:  '$HARVESTER_HARVEST_PASSWORD'
  account:   '$HARVESTER_HARVEST_ACCOUNT'
EOF

if [ ! -e /data/harvester.sqlite ]
then
    echo "Creating database."
    mkdir -p /data
    app/console doctrine:database:create
    app/console doctrine:schema:create

    if [ -e /data/harvester.sql ]
    then
        sqlite3 /data/harvester.sqlite < /data/harvester.sql
    fi

    echo "Initial import."
    app/console harvester:fetch

    # Fix up permissions for webapp.
    chmod a+w -R /harvester/app/cache /harvester/app/logs
fi
