parameters:

services:
    harvest_adapter:
        class: Harvester\FetchBundle\HarvestAdapter
        arguments:
            - @harvest_adapter_extended_api
            - %mattvick_harvest_app.user%
            - %mattvick_harvest_app.password%
            - %mattvick_harvest_app.account%
            - %mattvick_harvest_app.ssl%
            - %mattvick_harvest_app.mode%

    harvest_adapter_reports:
        class: HarvestReports

    harvest_adapter_extended_api:
        class: Harvester\FetchBundle\ExtendedHarvestAPI
