apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester
  labels:
    app: harvester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harvester
  template:
    metadata:
      labels:
        app: harvester
    spec:
      containers:
      - name: harvester
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        ports:
        - containerPort: 80
        env:
          - name: HARVESTER_HARVEST_ACCOUNT
            value: reload
          - name: HARVESTER_HARVEST_USER
            value: harvest@reload.dk
          - name: HARVESTER_HARVEST_PASSWORD
            value: {{ .Values.harvester.harvest.secret }}
        volumeMounts:
        - name: harvester-data
          mountPath: /data
      volumes:
        # Data volume for the SQLite database file.
        - name: harvester-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-{{ .Release.Name }}-harvester
