parameters:
  admin_controller.class: Harvester\AdminBundle\Controller\AdminController

services:
  admin_controller:
    class: %admin_controller.class%
    arguments:
      - @doctrine
      - @admin_user_form
      - @session
      - @admin_mailer
      - @router
      - @templating
      - @admin_utilities

  admin_user_form:
    class: Harvester\AdminBundle\AdminUserForm
    arguments:
      - @form.factory

  admin_mailer:
    class: Harvester\AdminBundle\AdminMailer
    arguments:
      - @mailer
      - @templating

  admin_utilities:
    class: Harvester\AdminBundle\AdminUtilities
